package org.iti.agrimarket.model.pojo;
// Generated Apr 28, 2016 6:18:09 PM by Hibernate Tools 4.3.1

import com.google.gson.annotations.Expose;
import java.util.HashSet;
import java.util.Set;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * Category generated by hbm2java
 */
@JsonIgnoreProperties(value = { "image","category","categories","products" })
public class Category implements java.io.Serializable {

    @Expose
    private Integer id;
    @Expose
    private String nameAr;
    @Expose
    private String nameEn;
    @Expose
    private String imageUrl;
    @Expose
    private String soundUrl;
    @Expose
    private byte[] image;
    private Category category;
    private Set categories = new HashSet(0);
    private Set products = new HashSet(0);

    public Category() {
    }

    public Category(Category category) {
        this.category = category;
    }

    public Category(Category category, String nameAr, String nameEn, String imageUrl, String soundUrl, Set categories, Set products) {
        this.category = category;
        this.nameAr = nameAr;
        this.nameEn = nameEn;
        this.imageUrl = imageUrl;
        this.soundUrl = soundUrl;
        this.categories = categories;
        this.products = products;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public String getNameAr() {
        return this.nameAr;
    }

    public void setNameAr(String nameAr) {
        this.nameAr = nameAr;
    }

    public String getNameEn() {
        return this.nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getSoundUrl() {
        return this.soundUrl;
    }

    public void setSoundUrl(String soundUrl) {
        this.soundUrl = soundUrl;
    }

    public Set getCategories() {
        return this.categories;
    }

    public void setCategories(Set categories) {
        this.categories = categories;
    }

    public Set getProducts() {
        return this.products;
    }

    public void setProducts(Set products) {
        this.products = products;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    
}
