package org.iti.agrimarket.model.pojo;
// Generated Apr 29, 2016 4:07:51 PM by Hibernate Tools 4.3.1



/**
 * Encryption generated by hbm2java
 */
public class Encryption  implements java.io.Serializable {


     private Integer id;
     private String user;
     private String privateKey;
     private String publicKey;

    public Encryption() {
    }

    public Encryption(String user, String privateKey, String publicKey) {
       this.user = user;
       this.privateKey = privateKey;
       this.publicKey = publicKey;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPrivateKey() {
        return this.privateKey;
    }
    
    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey;
    }
    public String getPublicKey() {
        return this.publicKey;
    }
    
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }




}


