package org.iti.agrimarket.model.pojo;
// Generated Apr 29, 2016 4:07:51 PM by Hibernate Tools 4.3.1

import com.google.gson.annotations.Expose;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Season generated by hbm2java
 */
public class Season implements java.io.Serializable {

    @Expose
    private Integer id;

    @Expose
    private String nameAr;

    @Expose
    private String nameEn;

    @Expose
    private Date startDate;

    @Expose
    private Date endDate;
    private Set userPlantsPlants = new HashSet(0);
    private Set products = new HashSet(0);

    public Season() {
    }

    public Season(String nameAr, String nameEn, Date startDate, Date endDate, Set userPlantsPlants, Set products) {
        this.nameAr = nameAr;
        this.nameEn = nameEn;
        this.startDate = startDate;
        this.endDate = endDate;
        this.userPlantsPlants = userPlantsPlants;
        this.products = products;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNameAr() {
        return this.nameAr;
    }

    public void setNameAr(String nameAr) {
        this.nameAr = nameAr;
    }

    public String getNameEn() {
        return this.nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Set getUserPlantsPlants() {
        return this.userPlantsPlants;
    }

    public void setUserPlantsPlants(Set userPlantsPlants) {
        this.userPlantsPlants = userPlantsPlants;
    }

    public Set getProducts() {
        return this.products;
    }

    public void setProducts(Set products) {
        this.products = products;
    }

}
