package org.iti.agrimarket.model.pojo;
// Generated Apr 29, 2016 4:07:51 PM by Hibernate Tools 4.3.1

import com.google.gson.annotations.Expose;
import java.util.HashSet;
import java.util.Set;

/**
 * Unit generated by hbm2java
 */
public class Unit implements java.io.Serializable {

    @Expose
    private Integer id;
    @Expose
    private String nameAr;
    @Expose
    private String nameEn;
    @Expose
    private String type;

    private Set historiesForPricePerUnitId = new HashSet(0);
    private Set historiesForUnitId = new HashSet(0);
    private Set userPlantsPlants = new HashSet(0);
    private Set userOfferProductFixedsForUnitId = new HashSet(0);
    private Set userOfferProductFixedsForPricePerUnitId = new HashSet(0);

    public Unit() {
    }

    public Unit(String type) {
        this.type = type;
    }

    public Unit(String nameAr, String nameEn, String type, Set historiesForPricePerUnitId, Set historiesForUnitId, Set userPlantsPlants, Set userOfferProductFixedsForUnitId, Set userOfferProductFixedsForPricePerUnitId) {
        this.nameAr = nameAr;
        this.nameEn = nameEn;
        this.type = type;
        this.historiesForPricePerUnitId = historiesForPricePerUnitId;
        this.historiesForUnitId = historiesForUnitId;
        this.userPlantsPlants = userPlantsPlants;
        this.userOfferProductFixedsForUnitId = userOfferProductFixedsForUnitId;
        this.userOfferProductFixedsForPricePerUnitId = userOfferProductFixedsForPricePerUnitId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNameAr() {
        return this.nameAr;
    }

    public void setNameAr(String nameAr) {
        this.nameAr = nameAr;
    }

    public String getNameEn() {
        return this.nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Set getHistoriesForPricePerUnitId() {
        return this.historiesForPricePerUnitId;
    }

    public void setHistoriesForPricePerUnitId(Set historiesForPricePerUnitId) {
        this.historiesForPricePerUnitId = historiesForPricePerUnitId;
    }

    public Set getHistoriesForUnitId() {
        return this.historiesForUnitId;
    }

    public void setHistoriesForUnitId(Set historiesForUnitId) {
        this.historiesForUnitId = historiesForUnitId;
    }

    public Set getUserPlantsPlants() {
        return this.userPlantsPlants;
    }

    public void setUserPlantsPlants(Set userPlantsPlants) {
        this.userPlantsPlants = userPlantsPlants;
    }

    public Set getUserOfferProductFixedsForUnitId() {
        return this.userOfferProductFixedsForUnitId;
    }

    public void setUserOfferProductFixedsForUnitId(Set userOfferProductFixedsForUnitId) {
        this.userOfferProductFixedsForUnitId = userOfferProductFixedsForUnitId;
    }

    public Set getUserOfferProductFixedsForPricePerUnitId() {
        return this.userOfferProductFixedsForPricePerUnitId;
    }

    public void setUserOfferProductFixedsForPricePerUnitId(Set userOfferProductFixedsForPricePerUnitId) {
        this.userOfferProductFixedsForPricePerUnitId = userOfferProductFixedsForPricePerUnitId;
    }

}
