package org.iti.agrimarket.model.pojo;
// Generated Apr 29, 2016 4:07:51 PM by Hibernate Tools 4.3.1

import com.google.gson.annotations.Expose;

/**
 * UserPlantsPlant generated by hbm2java
 */
public class UserPlantsPlant implements java.io.Serializable {

    @Expose
    private Integer id;
    
    private Product product;
    private Season season;
    private Unit unit;
    private User user;

    @Expose
    private float noUnits;

    @Expose
    private int year;

    public UserPlantsPlant() {
    }

    public UserPlantsPlant(Product product, Season season, Unit unit, User user, float noUnits, int year) {
        this.product = product;
        this.season = season;
        this.unit = unit;
        this.user = user;
        this.noUnits = noUnits;
        this.year = year;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public Season getSeason() {
        return this.season;
    }

    public void setSeason(Season season) {
        this.season = season;
    }

    public Unit getUnit() {
        return this.unit;
    }

    public void setUnit(Unit unit) {
        this.unit = unit;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public float getNoUnits() {
        return this.noUnits;
    }

    public void setNoUnits(float noUnits) {
        this.noUnits = noUnits;
    }

    public int getYear() {
        return this.year;
    }

    public void setYear(int year) {
        this.year = year;
    }

}
