package org.iti.agrimarket.model.pojo;
// Generated Apr 29, 2016 4:07:51 PM by Hibernate Tools 4.3.1



/**
 * UserData generated by hbm2java
 */
public class UserData  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String imei;
     private int deviceChannel;
     private String deviceLanguage;
     private String osId;
     private String osVersion;

    public UserData() {
    }

	
    public UserData(User user, String imei, int deviceChannel, String deviceLanguage) {
        this.user = user;
        this.imei = imei;
        this.deviceChannel = deviceChannel;
        this.deviceLanguage = deviceLanguage;
    }
    public UserData(User user, String imei, int deviceChannel, String deviceLanguage, String osId, String osVersion) {
       this.user = user;
       this.imei = imei;
       this.deviceChannel = deviceChannel;
       this.deviceLanguage = deviceLanguage;
       this.osId = osId;
       this.osVersion = osVersion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getImei() {
        return this.imei;
    }
    
    public void setImei(String imei) {
        this.imei = imei;
    }
    public int getDeviceChannel() {
        return this.deviceChannel;
    }
    
    public void setDeviceChannel(int deviceChannel) {
        this.deviceChannel = deviceChannel;
    }
    public String getDeviceLanguage() {
        return this.deviceLanguage;
    }
    
    public void setDeviceLanguage(String deviceLanguage) {
        this.deviceLanguage = deviceLanguage;
    }
    public String getOsId() {
        return this.osId;
    }
    
    public void setOsId(String osId) {
        this.osId = osId;
    }
    public String getOsVersion() {
        return this.osVersion;
    }
    
    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion;
    }




}


