package org.iti.agrimarket.model.pojo;
// Generated Apr 29, 2016 4:07:51 PM by Hibernate Tools 4.3.1

import com.google.gson.annotations.Expose;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    @Expose
    private Integer id;
    @Expose
//    @NotNull(message = "You can't leave mail filed  empty.")
//    @Email(message = "Enter your full email address, including the '@'.")
    private String mail;
    @Expose
//    @NotNull(message = "You can't leave this empty.")
    private String fullName;
    @Expose
//    @Phone(message = "You can't leave this empty.")
    private String mobile;
//    @Expose
//    @NotNull
    private int registrationChannel;
//    @Expose
//    @NotNull
    private double lat;
//    @Expose
//    @NotNull
    private double long_;
    @Expose
//    @NotNull
    private String governerate;
    @Expose
    private String imageUrl;
//    @Expose
    private int ratesAverage;
//    @Expose
    private boolean loggedIn;
    @Expose
    private byte[] image;
    private Set userDatas = new HashSet(0);
    private Set products = new HashSet(0);
    private Set userPlantsPlants = new HashSet(0);
    private Set userOfferProductFixeds = new HashSet(0);
    private Set histories = new HashSet(0);
    private Set userRatesUsersForRatedId = new HashSet(0);
    private Set userRatesUsersForRaterId = new HashSet(0);

    public User() {
    }

    public User(String mail, String fullName, String mobile, int registrationChannel, double lat, double long_, int ratesAverage, boolean loggedIn) {
        this.mail = mail;
        this.fullName = fullName;
        this.mobile = mobile;
        this.registrationChannel = registrationChannel;
        this.lat = lat;
        this.long_ = long_;
        this.ratesAverage = ratesAverage;
        this.loggedIn = loggedIn;
    }

    
    public User(String mail, String fullName, String mobile, int registrationChannel, double lat, double long_, String governerate, String imageUrl, int ratesAverage, boolean loggedIn, Set userDatas, Set products, Set userPlantsPlants, Set userOfferProductFixeds, Set histories, Set userRatesUsersForRatedId, Set userRatesUsersForRaterId) {
        this.mail = mail;
        this.fullName = fullName;
        this.mobile = mobile;
        this.registrationChannel = registrationChannel;
        this.lat = lat;
        this.long_ = long_;
        this.governerate = governerate;
        this.imageUrl = imageUrl;
        this.ratesAverage = ratesAverage;
        this.loggedIn = loggedIn;
        this.userDatas = userDatas;
        this.products = products;
        this.userPlantsPlants = userPlantsPlants;
        this.userOfferProductFixeds = userOfferProductFixeds;
        this.histories = histories;
        this.userRatesUsersForRatedId = userRatesUsersForRatedId;
        this.userRatesUsersForRaterId = userRatesUsersForRaterId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public int getRegistrationChannel() {
        return this.registrationChannel;
    }

    public void setRegistrationChannel(int registrationChannel) {
        this.registrationChannel = registrationChannel;
    }

    public double getLat() {
        return this.lat;
    }

    public void setLat(double lat) {
        this.lat = lat;
    }

    public double getLong_() {
        return this.long_;
    }

    public void setLong_(double long_) {
        this.long_ = long_;
    }

    public String getGovernerate() {
        return this.governerate;
    }

    public void setGovernerate(String governerate) {
        this.governerate = governerate;
    }

    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public int getRatesAverage() {
        return this.ratesAverage;
    }

    public void setRatesAverage(int ratesAverage) {
        this.ratesAverage = ratesAverage;
    }

    public boolean isLoggedIn() {
        return this.loggedIn;
    }

    public void setLoggedIn(boolean loggedIn) {
        this.loggedIn = loggedIn;
    }

    public Set getUserDatas() {
        return this.userDatas;
    }

    public void setUserDatas(Set userDatas) {
        this.userDatas = userDatas;
    }

    public Set getProducts() {
        return this.products;
    }

    public void setProducts(Set products) {
        this.products = products;
    }

    public Set getUserPlantsPlants() {
        return this.userPlantsPlants;
    }

    public void setUserPlantsPlants(Set userPlantsPlants) {
        this.userPlantsPlants = userPlantsPlants;
    }

    public Set getUserOfferProductFixeds() {
        return this.userOfferProductFixeds;
    }

    public void setUserOfferProductFixeds(Set userOfferProductFixeds) {
        this.userOfferProductFixeds = userOfferProductFixeds;
    }

    public Set getHistories() {
        return this.histories;
    }

    public void setHistories(Set histories) {
        this.histories = histories;
    }

    public Set getUserRatesUsersForRatedId() {
        return this.userRatesUsersForRatedId;
    }

    public void setUserRatesUsersForRatedId(Set userRatesUsersForRatedId) {
        this.userRatesUsersForRatedId = userRatesUsersForRatedId;
    }

    public Set getUserRatesUsersForRaterId() {
        return this.userRatesUsersForRaterId;
    }

    public void setUserRatesUsersForRaterId(Set userRatesUsersForRaterId) {
        this.userRatesUsersForRaterId = userRatesUsersForRaterId;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }
    
    

}
