package org.iti.agrimarket.model.pojo;
// Generated Apr 29, 2016 4:07:51 PM by Hibernate Tools 4.3.1

import com.google.gson.annotations.Expose;

/**
 * UserRatesUser generated by hbm2java
 */
public class UserRatesUser implements java.io.Serializable {

    @Expose
    private UserRatesUserId id;
    @Expose
    private int rate;
    @Expose
    private String review;
    
    

    private User userByRatedId;
    private User userByRaterId;

    public UserRatesUser() {
    }

    public UserRatesUser(UserRatesUserId id, User userByRatedId, User userByRaterId, int rate) {
        this.id = id;
        this.userByRatedId = userByRatedId;
        this.userByRaterId = userByRaterId;
        this.rate = rate;
    }

    public UserRatesUser(UserRatesUserId id, User userByRatedId, User userByRaterId, int rate, String review) {
        this.id = id;
        this.userByRatedId = userByRatedId;
        this.userByRaterId = userByRaterId;
        this.rate = rate;
        this.review = review;
    }

    public UserRatesUserId getId() {
        return this.id;
    }

    public void setId(UserRatesUserId id) {
        this.id = id;
    }

    public User getUserByRatedId() {
        return this.userByRatedId;
    }

    public void setUserByRatedId(User userByRatedId) {
        this.userByRatedId = userByRatedId;
    }

    public User getUserByRaterId() {
        return this.userByRaterId;
    }

    public void setUserByRaterId(User userByRaterId) {
        this.userByRaterId = userByRaterId;
    }

    public int getRate() {
        return this.rate;
    }

    public void setRate(int rate) {
        this.rate = rate;
    }

    public String getReview() {
        return this.review;
    }

    public void setReview(String review) {
        this.review = review;
    }

}
