package org.iti.agrimarket.model.pojo;
// Generated Apr 29, 2016 4:07:51 PM by Hibernate Tools 4.3.1



/**
 * UserRatesUserId generated by hbm2java
 */
public class UserRatesUserId  implements java.io.Serializable {


     private int raterId;
     private int ratedId;

    public UserRatesUserId() {
    }

    public UserRatesUserId(int raterId, int ratedId) {
       this.raterId = raterId;
       this.ratedId = ratedId;
    }
   
    public int getRaterId() {
        return this.raterId;
    }
    
    public void setRaterId(int raterId) {
        this.raterId = raterId;
    }
    public int getRatedId() {
        return this.ratedId;
    }
    
    public void setRatedId(int ratedId) {
        this.ratedId = ratedId;
    }




}


